---
- name: Start ec2 instance
  hosts: localhost
  tasks:

    - name: starting ec2 instance

      ec2:
        state: stopped
        region: us-east-1
        instance_tags:
          Name: WEB_1

