---
- name: ansible-ec2-launch & ssh setup on amazon linux 2
  hosts: localhost
  become: yes
  gather_facts: False

  vars:
    sourcefile:
    ans-hostfile: /etc/ansible/hosts
    ans-pubkey: ~/.ssh/ans-pubkey.pub

  vars_promt:

    - name: nametag
      prompt: Enter a name tag.
      private: no

    - name: instance_type
      prompt: Enter an instance type.
      default: t2.micro
      private: no

  tasks:
  
  - name: launching aws instance with Ansible

    ec2:
      key_name: devops_01
      region: us-east-1
      instance_type: '{{ instance_type }}'
      image: ami-0b5eea76982371e91
      assign_public_ip: yes
      wait: yes
      wait_timeout: 600
      instance_tags:
        Name: '{{ nametag }}'
    register: ec2

  - name: wait for ssh
    wait_for:
      host: '{{ item.public_ip }}'
      port: 22
      state: started
    with_items: ec2.instances

  - name: add host to host inventory file
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: webserver
    with_items: ec2.instances




