---
- name: ansible-ec2-launch & ssh setup on amazon linux 2
  hosts: localhost
  become: yes
  gather_facts: False

  vars_prompt:

    - name: nametag
      prompt: Enter a name tag.
      private: no

    - name: instance_type
      prompt: Enter an instance type.
      default: t2.micro
      private: no

  tasks:
  
  - name: launching aws instance with Ansible

    ec2:
      key_name: devops_01
      region: us-east-1
      instance_type: '{{ instance_type }}'
      image: ami-0b5eea76982371e91
      wait: yes
      wait_timeout: 600
      instance_tags:
        Name: '{{ nametag }}'
    register: ec2

  - name: add instance to host file
    lineinfile:
      dest: /etc/ansible/hosts
      regexp: '{{ item.public_ip }}'
      insertafter: 'new_server'
      line: "{{ item.public_ip }}"
      state: present
    with_items: '{{ ec2.instances }}'

