---
- name: creating user by looping variable
  hosts: client2
  vars:
    users: [alessia,aceyn,aylin]

  tasks:
          - name: create user
            user:
              name: '{{item}}'
            with_items: '{{users}}'
