---
- name: Setup httpd and open firewall port
  hosts: localhost
  become: yes

  tasks:
          - name: update packages
            yum:
              name: '*'
              state: latest
          - name: install firewalld
            yum:
              name: firewalld
              state: present
          - name: start firewalld
            service:
              name: firewalld
              state: started
          - name: install httpd
            yum:
              name: httpd
              state: present
          - name: start httpd
            service:
              name: httpd
              state: started
          - name: open port 80 for http access
            firewalld:
              service: http
              permanent: true
              state: enabled
          - name: Restart firewall to load changes
            service:
              name: firewalld
              state: reloaded


