---
- name: ansible-ec2-launch & ssh setup on amazon linux 2
  hosts: localhost
  become: yes
  gather_facts: False

  vars_prompt:

    - name: nametag
      prompt: Enter a name tag.
      private: no

    - name: instance_type
      prompt: Enter an instance type.
      default: t2.micro
      private: no

    - name: region
      prompt: Enter a region.
      default: us-east-1
      private: no

    - name: image
      prompt: Please enter ami image number.
      default: ami-0b5eea76982371e91
      private: no

    - name: inventory_group
      prompt: Enter group name in hostfile in which ip will be added.
      default: host_to_add_pubkey
      private: no

    - name: security_group
      prompt: Enter security group
      default: web_server1
      private: no

    - name: vpc_subnet
      prompt: Enter VPC subnet ID.
      default: subnet-05208f1ee4d8b8ed7
      private: no

    - name: default_user
      prompt: Enter default user of AMI instance
      default: ec2-user
      private: no

  vars:
    remote_ssh_path: /.ssh/authorized_keys 

  tasks:
  
  - name: launching aws instance with Ansible

    ec2:
      key_name: web_server_key
      region: '{{ region }}'
      instance_type: '{{ instance_type }}'
      group: '{{ security_group }}'
      vpc_subnet_id: '{{ vpc_subnet }}'
      image: '{{ image }}'
      wait: yes
      wait_timeout: 600
      instance_tags:
        Name: '{{ nametag }}'
    register: ec2

  - name: add host ipv4 to group
    lineinfile:
      dest: /etc/ansible/hosts
      regexp: '{{ item.public_ip }}'
      insertafter: '{{ inventory_group }}'
      line: "{{ item.public_ip }}"
      state: present
    with_items: '{{ ec2.instances }}'

  
    

      # - name: wait for ssh to come up
      #delegate_to: "{{ item.public_dns_name }}"
      #wait_for_connection:
      #delay: 60
      #timeout: 320
      #loop: "{{ ec2.instances }}"
      #git@github.com:AKSarav/Add-SSH-Key-EC2-Ansible.git
