### play book made up of roles to intall various pkgs
#

---
- name: Install packages amazon linux server
  hosts: fulltest
  remote_user: ec2-user
  become: yes

  roles:
    - install_httpd
    - chrome-driver
    - google

  tasks:

    - name: Install pip
      yum:
        name: pip
        state: present

    - name: Update packages
      yum:
        name: '*'
        state: latest

    - name: Install python3
      yum:
        name: python3
        state: present

